{% set name = "dcTMD" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dcTMD-{{ version }}.tar.gz
  sha256: 63a71bb1111317092990088c160e1fce74b1bfd548e5dce8ca6c3bcee250b5b3

build:
  noarch: python
  entry_points:
    - dcTMD = dcTMD.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.21.0
    - scikit-learn
    - beartype >=0.10.4
    - scipy
    - tqdm
    - click >=7.0.0
    - typing-extensions >=3.9.0
    - matplotlib-base >=3.7

test:
  imports:
    - dcTMD
  commands:
    - pip check
    - dcTMD --help
  requires:
    - pip

about:
  home: https://github.com/moldyn/dcTMD
  summary: Analyse targeted molecular dynamics data with dcTMD
  license: MIT
  license_file: LICENSE
  doc_url: https://moldyn.github.io/dcTMD

extra:
  recipe-maintainers:
    - braniii
