{% set name = "dcTMD" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: c8bbd91fffd4e1e1de8cd69a682621ead9a4c2a167f67fa85044476e04d372b9

build:
  noarch: python
  entry_points:
    - dcTMD = dcTMD.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - scikit-learn
    - beartype >=0.10.4
    - scipy
    - tqdm
    - click >=7.0.0
    - matplotlib-base >=3.7

test:
  imports:
    - dcTMD
  commands:
    - pip check
    - dcTMD --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/moldyn/dcTMD
  summary: Analyse targeted molecular dynamics data with dcTMD
  license: MIT
  license_file: LICENSE
  doc_url: https://moldyn.github.io/dcTMD

extra:
  recipe-maintainers:
    - braniii
