{% set name = "dcTMD" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 156123c78c652af0adf69e5cf50fd45af9e23636634bc1c80117100f5a3b6ccb

build:
  noarch: python
  entry_points:
    - dcTMD = dcTMD.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - scikit-learn
    - beartype >=0.10.4
    - scipy
    - tqdm
    - click >=7.0.0
    - matplotlib-base >=3.7

test:
  imports:
    - dcTMD
  commands:
    - pip check
    - dcTMD --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/moldyn/dcTMD
  summary: Analyse targeted molecular dynamics data with dcTMD
  license: MIT
  license_file: LICENSE
  doc_url: https://moldyn.github.io/dcTMD

extra:
  recipe-maintainers:
    - braniii
